

from sympy import plot_implicit, Eq, log
from sympy.abc import x, y

a = ...
b = ...
c = ...
d = ...
eq1 = Eq ((y- log(x**a * 10**c))*(x-log(x**b * 10*d)), -1)
plot_implicit(eq1, (x, -100, 100), (y, -100, 100))
